@endpoint =  https://9i1oqg51z6.execute-api.us-east-1.amazonaws.com/prod


# get all 
GET {{endpoint}}/spaces
###
# get by id
GET {{endpoint}}/spaces?spaceId=48bbe3a1-753c-4d0e-9587-856bdec9a18b
###
# get by location
GET {{endpoint}}/spaces?location=Portugal
###
# update space info 
PUT {{endpoint}}/spaces?spaceId=e74f0a2c-1819-48b1-8a6f-3aee508c16db
Content-Type: application/json

{
    "location": "Ponte de sor",
    "name": "Best City in the world"
}
###

# add new space
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Texas",
    "name": "Fuck this pile of sand!",
}
###

# delete space
DELETE  {{endpoint}}/spaces?spaceId=e74f0a2c-1819-48b1-8a6f-3aee508c16db
###